"""UploadBatchFile

Revision ID: 01bcc2752d02
Revises: d2d82d448b8a
Create Date: 2025-07-18 10:37:29.909763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01bcc2752d02'
down_revision: Union[str, None] = 'd2d82d448b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UploadBatch',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProjectNumber', sa.String(length=80), nullable=False),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.Column('FileType', sa.String(length=10), nullable=False),
    sa.Column('FileSize', sa.Float(), nullable=True),
    sa.Column('UploadTime', sa.DateTime(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('UploadedBy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UploadedBy'], ['User.UserId'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('ix_UploadBatch_ProjectNumber_Status', 'UploadBatch', ['ProjectNumber', 'Status'], unique=False)
    op.create_index('ix_UploadBatch_ProjectNumber_UploadTime', 'UploadBatch', ['ProjectNumber', sa.literal_column('[UploadTime] DESC')], unique=False)
    op.create_table('UploadBatchFile',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BatchId', sa.Integer(), nullable=False),
    sa.Column('FileName', sa.String(length=255), nullable=False),
    sa.Column('Domain', sa.String(length=10), nullable=True),
    sa.Column('StagedAt', sa.DateTime(), nullable=True),
    sa.Column('CopiedAt', sa.DateTime(), nullable=True),
    sa.Column('EnqueuedAt', sa.DateTime(), nullable=True),
    sa.Column('ProcessedAt', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.Column('ErrorNote', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['BatchId'], ['UploadBatch.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('ix_UploadBatchFile_BatchId_Status', 'UploadBatchFile', ['BatchId', 'Status'], unique=False)
    op.create_index('ix_UploadBatchFile_Domain_Status', 'UploadBatchFile', ['Domain', 'Status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_UploadBatchFile_Domain_Status', table_name='UploadBatchFile')
    op.drop_index('ix_UploadBatchFile_BatchId_Status', table_name='UploadBatchFile')
    op.drop_table('UploadBatchFile')
    op.drop_index('ix_UploadBatch_ProjectNumber_UploadTime', table_name='UploadBatch')
    op.drop_index('ix_UploadBatch_ProjectNumber_Status', table_name='UploadBatch')
    op.drop_table('UploadBatch')
    # ### end Alembic commands ###
