"""Add feedback fields to ClinicalQueryMessage

Revision ID: 094f06e65c8c
Revises: 470cae8de27f
Create Date: 2025-07-25 17:33:42.220908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094f06e65c8c'
down_revision: Union[str, None] = '470cae8de27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClinicalQueryMessage', sa.Column('FeedbackType', sa.String(length=20), nullable=True))
    op.add_column('ClinicalQueryMessage', sa.Column('FeedbackComment', sa.Text(), nullable=True))
    op.add_column('ClinicalQueryMessage', sa.Column('FeedbackAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClinicalQueryMessage', 'FeedbackAt')
    op.drop_column('ClinicalQueryMessage', 'FeedbackComment')
    op.drop_column('ClinicalQueryMessage', 'FeedbackType')
    # ### end Alembic commands ###
