"""add QueryBy field

Revision ID: 15ed5b98afa6
Revises: 094f06e65c8c
Create Date: 2025-08-05 12:26:19.910614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ed5b98afa6'
down_revision: Union[str, None] = '094f06e65c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClinicalQueryMessage', sa.Column('QueryBy', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ClinicalQueryMessage', 'User', ['QueryBy'], ['UserId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ClinicalQueryMessage', type_='foreignkey')
    op.drop_column('ClinicalQueryMessage', 'QueryBy')
    # ### end Alembic commands ###
