"""UploadBatch colunm added

Revision ID: 470cae8de27f
Revises: 01bcc2752d02
Create Date: 2025-07-23 15:13:46.978605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470cae8de27f'
down_revision: Union[str, None] = '01bcc2752d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UploadBatch', sa.Column('FileCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UploadBatch', 'FileCount')
    # ### end Alembic commands ###
