"""modifiedby-Null

Revision ID: 4ad80ba60fee
Revises: b3f42d98f1a1
Create Date: 2025-08-21 19:06:38.299920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad80ba60fee'
down_revision: Union[str, None] = 'b3f42d98f1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PatientProfileConfig', 'ModifiedBy',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PatientProfileConfig', 'ModifiedBy',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
