"""add QnAGroupId field

Revision ID: 5f2f63f949ab
Revises: ba251bc8601b
Create Date: 2025-08-08 11:53:27.074804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2f63f949ab'
down_revision: Union[str, None] = 'ba251bc8601b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClinicalQueryMessage', 'viewType')
    op.add_column('ClinicalQueryMessage', sa.Column('ViewType', sa.String(length=20), nullable=True))
    op.add_column('ClinicalQueryMessage', sa.Column('QnAGroupId', sa.Integer(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClinicalQueryMessage', sa.Column('viewType', sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('ClinicalQueryMessage', 'QnAGroupId')
    op.drop_column('ClinicalQueryMessage', 'ViewType')
    # ### end Alembic commands ###
