"""Updated SelectedColumns size

Revision ID: 79b07a9239f2
Revises: 4ad80ba60fee
Create Date: 2025-08-26 13:16:28.063573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b07a9239f2'
down_revision: Union[str, None] = '4ad80ba60fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PatientProfileConfig', 'SelectedColumns',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=2000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PatientProfileConfig', 'SelectedColumns',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
