"""ClinicalQueryMessage Update

Revision ID: 8a34c7147b85
Revises: 686fc5869be2
Create Date: 2025-09-10 10:03:56.922889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a34c7147b85'
down_revision: Union[str, None] = '686fc5869be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClinicalQueryMessage', sa.Column('FlowType', sa.String(length=20), nullable=True))
    op.add_column('ClinicalQueryMessage', sa.Column('StandardTableContent', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClinicalQueryMessage', 'StandardTableContent')
    op.drop_column('ClinicalQueryMessage', 'FlowType')
    # ### end Alembic commands ###
