"""ClinicalQueryMessage Update

Revision ID: 8b34c7147b88
Revises: 8a34c7147b85
Create Date: 2025-09-10 10:03:56.922889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b34c7147b88'
down_revision: Union[str, None] = '8a34c7147b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update PlaceholderText values
    op.execute("""
        UPDATE QueryPlaceholder
        SET PlaceholderText = '<hematology analytes>'
        WHERE Id = 22;
    """)

    op.execute("""
        UPDATE QueryPlaceholder
        SET PlaceholderText = '<liver analytes>'
        WHERE Id = 44;
    """)

    # Update CategoryFilter from 1 to 2 for specific Ids
    op.execute("""
        UPDATE QueryPlaceholder
        SET CategoryFilter = 2
        WHERE CategoryFilter = 1
          AND Id IN (24, 28, 32, 37, 42, 44);
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rollback changes if needed
    op.execute("""
        UPDATE QueryPlaceholder
        SET PlaceholderText = '<liver lab values>'
        WHERE Id = 22;
    """)

    op.execute("""
        UPDATE QueryPlaceholder
        SET PlaceholderText = '<liver lab values>'
        WHERE Id = 44;
    """)

    op.execute("""
        UPDATE QueryPlaceholder
        SET CategoryFilter = 1
        WHERE CategoryFilter = 2
          AND Id IN (24, 28, 32, 37, 42, 44);
    """)
    # ### end Alembic commands ###
