"""ClinicalQueryMessage Update

Revision ID: 8c34c7147b99
Revises: 8b34c7147b88
Create Date: 2025-09-10 10:03:56.922889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c34c7147b99'
down_revision: Union[str, None] = '8b34c7147b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update PlaceholderText values
    # Update QueryModule statuses
    op.execute("""
        DELETE FROM QueryPlaceholder WHERE QueryId IN (6,12);
    """)
    op.execute("""
        DELETE FROM PredefinedQuery WHERE Id IN (6,12);
    """)
    op.execute("""
        UPDATE QueryPlaceholder SET inputType='multi-select' WHERE Id IN (20,42);
               """)
    op.execute("""
        UPDATE QueryModule SET Status = 1 WHERE Id IN (2, 3);
    """)

    # Update QueryCategory statuses
    op.execute("""
        UPDATE QueryCategory
        SET Status = 1
        WHERE Id IN (3, 4, 5, 6, 7, 8);
    """)
    op.execute("""
    INSERT INTO PredefinedQuery (CategoryId, TemplateText, DatasetType, TablesInvolved, QueryType, Status) VALUES
        (3, 'For <subject>, what were the <renal lab values> most proximal to the start of the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'at_time', 1),
        (3, 'For <subject>, what were the <renal lab values> most proximal prior to the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'prior', 1),
        (3, 'For <subject>, what were the <renal lab values> during the <AE> at <YYYY-MM-DD> To <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'during', 1),
        (3, 'For <subject>, what were the <renal lab values> within <+/- dd> day(s) of the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'within_days', 1),
        (3, 'For <subject>, what were the <renal lab values> during the study?', 'SDTM', 'LB', 'study', 1),
        (4, 'For <subject>, what were the <cardiac lab values> most proximal to the start of the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'at_time', 1),
        (4, 'For <subject>, what were the <cardiac lab values> most proximal prior to the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'prior', 1),
        (4, 'For <subject>, what were the <cardiac lab values> during the <AE> at <YYYY-MM-DD> To <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'during', 1),
        (4, 'For <subject>, what were the <cardiac lab values> within <+/- dd> day(s) of the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'within_days', 1),
        (4, 'For <subject>, what were the <cardiac lab values> during the study?', 'SDTM', 'LB', 'study', 1),
        (5, 'For <subject>, what were the <electrolytes lab values> most proximal to the start of the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'at_time', 1),
        (5, 'For <subject>, what were the <electrolytes lab values> most proximal prior to the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'prior', 1),
        (5, 'For <subject>, what were the <electrolytes lab values> during the <AE> at <YYYY-MM-DD> To <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'during', 1),
        (5, 'For <subject>, what were the <electrolytes lab values> within <+/- dd> day(s) of the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'within_days', 1),
        (5, 'For <subject>, what were the <electrolytes lab values> during the study?', 'SDTM', 'LB', 'study', 1),
        (6, 'For <subject>, what were the <coagulation lab values> most proximal to the start of the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'at_time', 1),
        (6, 'For <subject>, what were the <coagulation lab values> most proximal prior to the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'prior', 1),
        (6, 'For <subject>, what were the <coagulation lab values> during the <AE> at <YYYY-MM-DD> To <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'during', 1),
        (6, 'For <subject>, what were the <coagulation lab values> within <+/- dd> day(s) of the <AE> at <YYYY-MM-DD>?', 'SDTM', 'AE,LB', 'within_days', 1),
        (6, 'For <subject>, what were the <coagulation lab values> during the study?', 'SDTM', 'LB', 'study', 1);
        
        INSERT INTO QueryPlaceholder (QueryId, PlaceholderText, InputType, SourceTable, SourceColumn, CategoryFilter) VALUES
        (13, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (13, '<renal lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (13, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (13, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (14, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (14, '<renal lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (14, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (14, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (15, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (15, '<renal lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (15, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (15, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
        (15, '<YYYY-MM-DD>', 'auto-select', 'AE', 'AEENDTC', NULL),
 
        (16, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (16, '<renal lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (16, '<+/- dd>', 'text-field', 'NULL', 'NULL', NULL),
        (16, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (16, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (17, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (17, '<renal lab values>', 'multi-select', 'LB', 'LBTEST', 2),
  
        (18, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (18, '<cardiac lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (18, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (18, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (19, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (19, '<cardiac lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (19, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (19, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (20, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (20, '<cardiac lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (20, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (20, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
        (20, '<YYYY-MM-DD>', 'auto-select', 'AE', 'AEENDTC', NULL),
 
        (21, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (21, '<cardiac lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (21, '<+/- dd>', 'text-field', 'NULL', 'NULL', NULL),
        (21, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (21, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (22, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (22, '<cardiac lab values>', 'multi-select', 'LB', 'LBTEST', 2),
                
        (23, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (23, '<electrolytes lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (23, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (23, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),

        (24, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (24, '<electrolytes lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (24, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (24, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
        
        (25, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (25, '<electrolytes lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (25, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (25, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
        (25, '<YYYY-MM-DD>', 'auto-select', 'AE', 'AEENDTC', NULL),
 
        (26, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (26, '<electrolytes lab values>', 'multi-select', 'LB', 'LBTEST', 2),
        (26, '<+/- dd>', 'text-field', 'NULL', 'NULL', NULL),
        (26, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (26, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (27, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (27, '<electrolytes lab values>', 'multi-select', 'LB', 'LBTEST', 2),
                
        (28, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (28, '<coagulation lab values>', 'multi-select', 'LB', 'LBTEST', 6),
        (28, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (28, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (29, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (29, '<coagulation lab values>', 'multi-select', 'LB', 'LBTEST', 6),
        (29, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (29, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
 
        (30, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (30, '<coagulation lab values>', 'multi-select', 'LB', 'LBTEST', 6),
        (30, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (30, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
        (30, '<YYYY-MM-DD>', 'auto-select', 'AE', 'AEENDTC', NULL),
 
        (31, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (31, '<coagulation lab values>', 'multi-select', 'LB', 'LBTEST', 6),
        (31, '<+/- dd>', 'text-field', 'NULL', 'NULL', NULL),
        (31, '<AE>', 'single-select', 'AE', 'AEDECOD', NULL),
        (31, '<YYYY-MM-DD>', 'single-select', 'AE', 'AESTDTC', NULL),
        
        (32, '<subject>', 'single-select', 'AE', 'USUBJID', NULL),
        (32, '<coagulation lab values>', 'multi-select', 'LB', 'LBTEST', 6);
        """)
    op.execute("""
        UPDATE LabAnalytes
        SET LabTest = '["WBC","leukocytes", "neutrophils", "lymphocytes", "hemoglobin", "platelets"]'
        WHERE CategoryId = 1;
    """)
    op.execute("""
        UPDATE LabAnalytes
        SET LabTest = '["alanine aminotransferase", "bilirubin", "direct bilirubin", "aspartate aminotransferase", "alkaline phosphatase", "albumin", "gamma glutamyl transferase"]'
        WHERE CategoryId = 2;
    """)
    op.execute("""
        UPDATE LabAnalytes
        SET LabTest = '["creatinine", "urea","urea nitrogen","blood urea nitrogen", "potassium", "bicarbonate","carbon dioxide", "uric acid","urate", "calcium", "phosphorus","phosphate"]'
        WHERE CategoryId = 3;
    """)
    op.execute("""
        UPDATE LabAnalytes
        SET LabTest = '["magnesium", "potassium", "troponin", "calcium", "creatine kinase", "creatine kinase-MB"]'
        WHERE CategoryId = 4;
    """)
    op.execute("""
        UPDATE LabAnalytes
        SET LabTest = '["sodium", "potassium", "chloride", "bicarbonate","carbon dioxide", "glucose"]'
        WHERE CategoryId = 5;
    """)
    op.execute("""
        UPDATE LabAnalytes
        SET LabTest = '["activated partial thromboplastin time", "prothrombin time", "international normalized ratio"]'
        WHERE CategoryId = 6;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # Rollback QueryModule statuses
    op.execute("""
        UPDATE QueryModule
        SET Status = 0
        WHERE Id IN (2, 3);
    """)

    # Rollback QueryCategory statuses
    op.execute("""
        UPDATE QueryCategory
        SET Status = 0
        WHERE Id IN (3, 4, 5, 6, 7, 8);
    """)
    # ### end Alembic commands ###
