"""initial migration

Revision ID: 9bdf8f92ceff
Revises: 
Create Date: 2025-07-08 15:32:58.914912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bdf8f92ceff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('UserId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserEmail', sa.String(length=256), nullable=False),
    sa.Column('UserName', sa.String(length=100), nullable=False),
    sa.Column('ObjectId', sa.String(length=36), nullable=False),
    sa.Column('UserType', sa.String(length=50), nullable=True),
    sa.Column('RecordStatus', sa.String(length=1), server_default='A', nullable=False),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.CheckConstraint("[RecordStatus] IN ('A', 'D')", name='chk_user_record_status'),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_table('Project',
    sa.Column('ProjectId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProjectNumber', sa.String(length=80), nullable=False),
    sa.Column('StudyNumber', sa.String(length=80), nullable=False),
    sa.Column('CustomerName', sa.String(length=80), nullable=False),
    sa.Column('CutDate', sa.Date(), nullable=True),
    sa.Column('ExtractionDate', sa.Date(), nullable=True),
    sa.Column('IsDatasetUploaded', sa.Boolean(), nullable=False),
    sa.Column('UploadedBy', sa.Integer(), nullable=True),
    sa.Column('UploadedAt', sa.DateTime(), nullable=True),
    sa.Column('ProjectStatus', sa.String(length=50), nullable=False),
    sa.Column('RecordStatus', sa.String(length=1), server_default='A', nullable=False),
    sa.Column('CreatedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('ModifiedBy', sa.Integer(), nullable=True),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.Column('DeletedBy', sa.Integer(), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.CheckConstraint("[ProjectStatus] IN ('InProgress', 'Verification', 'Completed')", name='chk_project_status'),
    sa.CheckConstraint("[RecordStatus] IN ('A', 'D')", name='chk_project_record_status'),
    sa.ForeignKeyConstraint(['CreatedBy'], ['User.UserId'], ),
    sa.ForeignKeyConstraint(['DeletedBy'], ['User.UserId'], ),
    sa.ForeignKeyConstraint(['ModifiedBy'], ['User.UserId'], ),
    sa.ForeignKeyConstraint(['UploadedBy'], ['User.UserId'], ),
    sa.PrimaryKeyConstraint('ProjectId'),
    sa.UniqueConstraint('ProjectNumber')
    )
    op.create_table('ClinicalQuerySession',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProjectNumber', sa.String(length=80), nullable=False),
    sa.Column('Title', sa.Text(), nullable=False),
    sa.Column('IsFavorite', sa.Boolean(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ProjectNumber'], ['Project.ProjectNumber'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('ix_ClinicalQuerySession_ProjectNumber_IsFavorite', 'ClinicalQuerySession', ['ProjectNumber', 'IsFavorite'], unique=False)
    op.create_index('ix_ClinicalQuerySession_ProjectNumber_UpdatedAt', 'ClinicalQuerySession', ['ProjectNumber', sa.literal_column('[UpdatedAt] DESC')], unique=False)
    op.create_table('ClinicalQueryMessage',
    sa.Column('Id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('SessionId', sa.Integer(), nullable=False),
    sa.Column('Sender', sa.String(length=20), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('Metadata', sa.JSON(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['SessionId'], ['ClinicalQuerySession.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index('ix_ClinicalQueryMessage_SessionId_CreatedAt', 'ClinicalQueryMessage', ['SessionId', sa.literal_column('[CreatedAt] DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ClinicalQueryMessage_SessionId_CreatedAt', table_name='ClinicalQueryMessage')
    op.drop_table('ClinicalQueryMessage')
    op.drop_index('ix_ClinicalQuerySession_ProjectNumber_UpdatedAt', table_name='ClinicalQuerySession')
    op.drop_index('ix_ClinicalQuerySession_ProjectNumber_IsFavorite', table_name='ClinicalQuerySession')
    op.drop_table('ClinicalQuerySession')
    op.drop_table('Project')
    op.drop_table('User')
    # ### end Alembic commands ###
