"""patientprofileconfig

Revision ID: a2d19a00762a
Revises: d2e4174c69ca
Create Date: 2025-08-20 18:35:01.870331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d19a00762a'
down_revision: Union[str, None] = 'd2e4174c69ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PatientProfileConfig',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProjectNumber', sa.String(length=80), nullable=False),
    sa.Column('DatasetType', sa.String(length=10), nullable=False),
    sa.Column('TableName', sa.String(length=50), nullable=False),
    sa.Column('SelectedColumns', sa.String(length=100), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=True),
    sa.Column('CreatedBy', sa.Integer(), nullable=False),
    sa.Column('ModifiedBy', sa.Integer(), nullable=False),
    sa.Column('ModifiedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('ix_PatientProfileConfig_DatasetType', 'PatientProfileConfig', ['DatasetType'], unique=False)
    op.create_index('ix_PatientProfileConfig_ProjectID_TableName', 'PatientProfileConfig', ['ProjectNumber', 'TableName'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_PatientProfileConfig_ProjectID_TableName', table_name='PatientProfileConfig')
    op.drop_index('ix_PatientProfileConfig_DatasetType', table_name='PatientProfileConfig')
    op.drop_table('PatientProfileConfig')
    # ### end Alembic commands ###
