"""add viewType field

Revision ID: ba251bc8601b
Revises: 15ed5b98afa6
Create Date: 2025-08-07 17:39:40.798518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba251bc8601b'
down_revision: Union[str, None] = '15ed5b98afa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClinicalQueryMessage', sa.Column('viewType', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClinicalQueryMessage', 'viewType')
    # ### end Alembic commands ###
