"""add DomainFullName

Revision ID: d2e4174c69ca
Revises: 5f2f63f949ab
Create Date: 2025-08-18 14:23:40.424559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = 'd2e4174c69ca'
down_revision: Union[str, None] = '5f2f63f949ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Map: DomainName -> DomainFullName
DOMAIN_FULLNAME_MAP = {
    # ADaM Domains
    "adqs": "Questionnaires",
    "addv": "Disposition Events",
    "adpe": "Pharmacokinetics Events",
    "adeff": "Efficacy",
    "adis": "Disease Response",
    "adtte1": "Time-to-Event 1",
    "adtr": "Tumor Response",
    "adcm": "Concomitant Medications",
    "adpc": "Pharmacokinetics Concentrations",
    "adtte2": "Time-to-Event 2",
    "adex": "Exposure",
    "adae": "Adverse Events",
    "adef2": "Efficacy 2",
    "advs": "Vital Signs",
    "adeg": "Electrocardiogram",
    "adef1": "Efficacy 1",
    "adlb": "Laboratory",
    "admh": "Medical History",
    "adecog": "Cognitive Function",
    "adpr": "Procedures",
    "adsl": "Subject-Level Analysis",
    "adtte": "Time-to-Event",

    # SDTM Domains (examples)
    "dm": "Demographics",
    "ae": "Adverse Events",
    "cm": "Concomitant Medications",
    "lb": "Laboratory Tests",
    "vs": "Vital Signs",
    "mh": "Medical History",
    "ex": "Exposure",
    "pr": "Procedures",
    "qs": "Questionnaires",
    "tr": "Tumor/Lesion Results",
    "tu": "Tumor Identification",
    "ts": "Trial Summary",
    "sv": "Subject Visits",
    "te": "Trial Elements",
    "ta": "Trial Arms",
    "se": "Subject Elements",
    "ss": "Subject Status",
    "ec": "Exposure as Collected",
    "eg": "Electrocardiogram",
    "dv": "Protocol Deviations",
    "ds": "Disposition",
    "mi": "Microscopic Findings",
    "mb": "Microbiology",
    "pe": "Physical Examination",
    "pc": "Pharmacokinetics Concentrations",
    "ie": "Inclusion/Exclusion",
    "rs": "Response",
    "su": "Substance Use",
    "tv": "Trial Visits",
    "ti": "Trial Inclusion/Exclusion",
    "fa": "Findings About",
    "cv": "Cardiovascular",
    "dd": "Death Details",
    "is": "Immunogenicity Specimen Assessments",
    "nv": "Narratives",
    "oe": "Ophthalmic Examinations",
    "zi": "Custom Domain",
    "xv": "External Visits",

    # Supplemental
    "suppdm": "Supplemental Demographics",
    "suppae": "Supplemental Adverse Events",
    "suppcm": "Supplemental Concomitant Medications",
    "suppds": "Supplemental Disposition",
    "suppdv": "Supplemental Protocol Deviations",
    "suppex": "Supplemental Exposure",
    "suppeg": "Supplemental Electrocardiogram",
    "supplb": "Supplemental Laboratory",
    "suppmh": "Supplemental Medical History",
    "supppr": "Supplemental Procedures",
    "supprs": "Supplemental Response",
    "supptu": "Supplemental Tumor Identification",
    "supptr": "Supplemental Tumor Results",
    "suppqs": "Supplemental Questionnaires",
    "suppsv": "Supplemental Subject Visits",
    "suppss": "Supplemental Subject Status",
    "suppse": "Supplemental Subject Elements",
    "suppec": "Supplemental Exposure as Collected",
    "suppmi": "Supplemental Microscopic Findings",
    "supppc": "Supplemental PK Concentrations",
    "supppe": "Supplemental Physical Examination",
    "suppfa": "Supplemental Findings About",
    "suppnv": "Supplemental Narratives",
    "suppis": "Supplemental Immunogenicity",
    "suppdd": "Supplemental Death Details",
    "suppcv": "Supplemental Cardiovascular",
    "suppzi": "Supplemental Custom Domain",
    "suppmb": "Supplemental Microbiology",
    "suppoe": "Supplemental Ophthalmic Examinations",
    "suppie": "Supplemental Inclusion/Exclusion",
}

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DomainClassification', sa.Column('DomainFullName', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
    for domain, fullname in DOMAIN_FULLNAME_MAP.items():
        op.execute(
            text("""
                UPDATE DomainClassification
                SET DomainFullName = :fullname
                WHERE DomainName = :domain
            """).bindparams(domain=domain, fullname=fullname)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DomainClassification', 'DomainFullName')
    # ### end Alembic commands ###
